### ISSUE TITLE
Precision error when getting double value from sdf element

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/sdformat#103]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/103)) by Ian Chen (Bitbucket: [Ian Chen](https://bitbucket.org/%7Beaa6fca5-6deb-43f6-907f-971c144735dd%7D/), GitHub: [iche033](https://github.com/iche033)).**

----------------------------------------
Values are stored as strings in sdf elements which probably resulted in the cropping of decimals during the double to string cast operation.

Added test in [double_precision](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/commits/bda619ad70b6730a3bd476f8dff36adc53b209b4) (3cb30382272f4410c410d641cb0b235376170eef)
 branch

The test shows that decimals get cropped and the double comparison fails

**Comment by scpeters** [comment]
this should be fixed by #1137
