### ISSUE TITLE
Parsing from URDF to SDF does not handle elements under <visual> or <collision> tags

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/sdformat#113]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/113)) by Alessandro Tondo (Bitbucket: [alextoind](https://bitbucket.org/%7Be784db86-294e-4d04-9625-965cd9f37dbb%7D/)).**

----------------------------------------
I have created a simple package to show a strange behaviour when parsing from URDF to SDF with Gazebo6 or Gazebo7 and ROS Jade (no problem with Gazebo5).

This is the example with a full description: https://bitbucket.org/alextoind/a_buggy_robot.

It seems that the problem affects only those URDF elements under `<gazebo>` tags which would end under the `<visual>` or `<collision>` SDF elements.

**Comment by azeey** [comment]
I believe this is a duplicate of https://github.com/gazebosim/sdformat/issues/333. Since that issue describes the problem more concisely, I'll close this one.
