### ISSUE TITLE
model.sdf not parsed 

### ISSUE THREAD

**Issue by tejalbarnwal** [gazebosim/sdformat#1172]
## Description
* Expected behavior: Any `.sdf` and `.urdf` file should be able to parse
* Actual behavior: Following [this](http://sdformat.org/tutorials?tut=quickstart) tutorial for Garden, wasn't able to parse sdf file when the sdf file is named as `model.sdf`. When the same file is renamed with any other name, it works.

## Steps to reproduce

1. Download any `model.sdf` file from [here](http://models.gazebosim.org/)
2. Follow the tutorial [here](http://sdformat.org/tutorials?tut=quickstart)
3. Run `./check_sdf model.sdf`

## Output

> for `./check_sdf model.sdf`
```
model.sdf is not a valid SDF file!
```

## Environment
* OS: Ubuntu 20.04
* Build: Binary Garden Installation

Referring [this](https://github.com/gazebosim/gz-tools/issues/105), the same issue was also found in gazebo classic 11

**Comment by azeey** [comment]
Thanks @tejalbarnwal . I'll close the other issues.
