### ISSUE TITLE
Choosing models with more recent sdf version

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/sdformat#123]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/123)) by Steve Peters (Bitbucket: [Steven Peters](https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/), GitHub: [scpeters](https://github.com/scpeters)).**

----------------------------------------
There is logic in [parser.cc](https://github.com/osrf/sdformat/blob/b3b4719312712eb259312dca219a7835c47db95f/src/parser.cc#L630) for choosing which sdf version of a model to use when a model is specified with the `<include><uri>model://` syntax. There is similar logic in gazebo that was updated in [gazebo pull request 2207](https://bitbucket.org/osrf/gazebo/pull-requests/2207/semantic_version_7/diff#Lgazebo/common/ModelDatabase.ccF623T626) and should be propagated to sdformat.

**Comment by scpeters** [comment]
this feature is implemented
