### ISSUE TITLE
How to visualize model.sdf file on a webpage?

### ISSUE THREAD

**Issue by addy1997** [gazebosim/sdformat#1262]
## Desired behavior
Visualize the 3D model of a robot/object(in SDF) on a webpage.

## Alternatives considered
Considered going through [the](http://wiki.ros.org/ros3djs/Tutorials/VisualizingAURDF#URDF_Example) URDF to HTML viewer tutorial, but it doesn't work for me.

## Implementation suggestion
Implementing a transpiler to convert the XML-based (model.sdf) file to HTML.

## Additional context
I've explored various loaders available in the Three.js library (for example-https://jsfiddle.net/adwait3301/4jfsqnxv/26/ ). This is a simple webGL-based Collada file visualizer capable of processing any Collada (.dae) file. Since the model.sdf file supports various 3D model formats, such as .dae, .obj, etc., my requirement is to convert an SDF file to an HTML file for visualization.

**Comment by azeey** [comment]
We already have https://github.com/gazebo-web/gzweb. Can you give it a try?
