### ISSUE TITLE
gz sdf still not on Windows?

### ISSUE THREAD

**Issue by peci1** [gazebosim/sdformat#1321]
https://github.com/gazebosim/sdformat/blob/881cbb7f4bab89d052095a43a11cf30059a174f4/src/CMakeLists.txt#L129-L131

Any reason why this is still there? What is the blocker?

**Comment by peci1** [comment]
Bad thing is `gz sdf` command is actually registered to gz-tools, so it is presented in help messages etc., but the ruby script is not installed, so any attempt at running it fails with a cryptic error.

**Comment by traversaro** [comment]
See https://github.com/gazebosim/gz-tools/issues/71 for a related discussion. In a nutshell we need to propagate the fix https://github.com/gazebosim/gz-plugin/pull/63 here, just removing the if if I am not wrong will break builds on Visual Studio multiple-config generators.

**Comment by peci1** [comment]
> if if I am not wrong will break builds on Visual Studio multiple-config generators.

You're right ;)
