### ISSUE TITLE
Geometry Python object lacks API's for Heightmaps

### ISSUE THREAD

**Issue by Erumeldor** [gazebosim/sdformat#1439]
Starting from SDFormat 1.9, SDFormat XML <geometry> has a <heightmap> tag, but the SDFormat Python API Geometry class does not seem to support it.

The C++ functions HeightmapShape and SetHeightmapShape are not linked.

There is even a small comment in the source file.
https://github.com/gazebosim/sdformat/blob/sdf14/python/src/sdf/pyGeometry.cc

**Comment by azeey** [comment]
Thanks for reporting this @Erumeldor. Would you be interested in adding those missing functions?

**Comment by ahcorde** [comment]
PR https://github.com/gazebosim/sdformat/pull/1440

**Comment by scpeters** [comment]
for reference, the C++ bindings were added in https://github.com/gazebosim/sdformat/pull/388
