### ISSUE TITLE
Update documentation on joints' frames specifying defaults and conventions

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/sdformat#170]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/170)) by Alejandro Castro (Bitbucket: [amcastro0622](https://bitbucket.org/%7Bf78f4af9-eed7-49c4-b222-5b3dc10d5093%7D/)).**

----------------------------------------
Reading the documentation for an SDF's joint axis [here](http://sdformat.org/spec?ver=1.6&elem=joint#axis_use_parent_model_frame) I had the following questions:

1. `use_parent_model_frame=true` means...? the `<model>`  frame I believe, could it be confirmed? the word "parent" overloads with "parent body" in the same `<joint>` doc and thus the confusion.
2. `use_parent_model_frame=false` means... the "joint frame". How is this "joint frame" defined? where is the origin of this joint frame?

In version 1.6 the [documentation for <pose>](http://sdformat.org/spec?ver=1.6&elem=joint#joint_pose) does not state the default when the `<pose>` itself or the `<frame>` in which this pose is measured, are not specified.
However, [version 1.4 doc](http://sdformat.org/spec?ver=1.4&elem=joint#joint_pose) does state that the default is the identity transform "in the child link frame" (ala urdf, makes sense).

The questions are:

1. Why didn't this doc make it to 1.6. Clearly default pose and frames need to be stated for a non-ambiguous description.
2. Unless the convention changed in 1.6?

It seems that, in current version 1.6 an old issue, 494, is mentioned. Is that fully resolved?

Finally, nothing is said about the joint frame on the "parent" body. It'd seem that the implicit convention is that this frame gets defined by making it coincident with the frame on the child body (referred to as, I believe, the "joint frame"). If this is true, it should be explicitly stated somewhere. If not, the documentation should be updated to reflect the actual convention.

**Comment by scpeters** [comment]
this documentation is now available at http://sdformat.org/tutorials?tut=pose_frame_semantics&cat=specification&
