### ISSUE TITLE
Update documentation on link' frames specifying defaults and conventions

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/sdformat#171]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/171)) by Alejandro Castro (Bitbucket: [amcastro0622](https://bitbucket.org/%7Bf78f4af9-eed7-49c4-b222-5b3dc10d5093%7D/)).**

----------------------------------------
The `<pose>` element allow us to specify the position of a `<link>`. Now, in what frame? according to [current 1.6 documentation](http://sdformat.org/spec?ver=1.6&elem=link#link_pose) the `<pose>` is specified in a given `<frame>`. However the documentation does not state the default values for either `<pose>` nor `<frame>` when these are not specified.

There seems to be another mechanism to specify the pose of a link, [using a `<frame>` ](http://sdformat.org/spec?ver=1.6&elem=link#link_frame)element. However default values for none of its child elements are provided. If both are provided, `<frame>` and `<pose>` at the same level (they are siblings), which one should we give preference to? does `sdf::SDF()` throw an exception or emit a message of  any kind? should it?

[The documentation in version 1.4](http://sdformat.org/spec?ver=1.4&elem=link#link_pose) is more precise, specifying default value of the pose (the identity) and in what frame (the model frame). Also, by not providing `<frame>` options it does not introduce any ambiguities, though it might not be as general.

**Comment by scpeters** [comment]
this documentation is now available at http://sdformat.org/tutorials?tut=pose_frame_semantics&cat=specification&
