### ISSUE TITLE
joint: should support specifying frames in `<child>` and `<parent>`

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/sdformat#204]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/204)) by Eric Cousineau (Bitbucket: [eacousineau](https://bitbucket.org/%7B71c9fc05-02c8-45e1-adfa-13c8ac3399dc%7D/), GitHub: [EricCousineau-TRI](https://github.com/EricCousineau-TRI)).**

----------------------------------------
# Summary

At present, the `<child>` and `<parent>` elements of `<joint>` are constrained to be links:
http://sdformat.org/spec?ver=1.6&elem=joint#joint_parent

It would be excellent if the specification permitted using frames. Per #200, if a link creates an implicit frame, then this change will be backwards-compatible at a specification level.

# Motivation

When specifying a world in SDF, it would be nice to specify joints with more semantics than just a link and an offset; e.g. if I want to weld a mug to the top of a table, I can specify two frames (completely invariant of the model frames) on the mug and table, and then just weld those two frames together. For a robot with revolute joints, you can embed better semantics when assembling the robot.

I am willing to provide a draft change to the spec, and possibly to the API as well to accommodate this change while considering backwards compatibility.

# Describe alternatives you've considered

TTBOMK, the alternative is to use the present state, which is to manually compute the kinematics; while feasible, this is brittle due to numerics. Xacros / ruby templates shouldn't be necessary for conveniently joining things.

# Additional context

If this proposal is accepted, I would like to ensure that this feature is implemented in Drake here:
https://drake.mit.edu/doxygen_cxx/namespacedrake_1_1multibody_1_1parsing.html#a3e9bff0197c6c7f86f9ff6f8854def53
https://drake.mit.edu/pydrake/pydrake.multibody.multibody_tree.parsing.html#pydrake.multibody.multibody_tree.parsing.AddModelFromSdfFile
Downstream issue: https://github.com/RobotLocomotion/drake/issues/9910

\cc @nkoenig

**Comment by scpeters** [comment]
this is part of the current draft of the composition proposal:

* section 1.2.2: http://sdformat.org/tutorials?tut=composition_proposal&cat=pose_semantics_docs&#1-2-interface-elements

**Comment by EricCousineau-TRI** [comment]
Suggested route:
* Make parsing use frames, and resolve to links and poses
* Keep public API the same (only expose link + relative pose)

**Comment by scpeters** [comment]
I have a branch that updates the proposed SDFormat 1.8 parsing stages with this change: https://github.com/osrf/sdf_tutorials/commit/add29753a7774ceb59e032629397349087dec968

**Comment by scpeters** [comment]
I have a branch with a prototype implementation of this change. The kernel of the change is in https://github.com/osrf/sdformat/commit/cf095f35a8709b3ff76d1bdcd105ed97326a3199, which modifies how the `FrameAttachedToGraph` and `PoseRelativeToGraph` are built. It ensures that all vertices are added to the graph before adding any edges connecting a joint with its child and removes assumptions that joint child must be a link.

**Comment by scpeters** [comment]
I updated the documentation of parsing stages a bit further based on the observation that all vertices need to be added to the graph before adding any joint edges: https://github.com/osrf/sdf_tutorials/commit/77b0db1f4e8e91b6cbdefe5f318f056001855712

**Comment by scpeters** [comment]
In order to figure out which are actually the parent and child links of a joint now, I think we should add `Joint::ResolveParentBody` and `Joint::ResolveChildBody` as analogs of [Frame::ResolveAttachedToBody](https://github.com/osrf/sdformat/blob/sdformat9_9.2.0/src/Frame.cc#L216)

**Comment by EricCousineau-TRI** [comment]
> In order to figure out which are actually the parent and child links of a joint now, I think we should add Joint::ResolveParentBody and Joint::ResolveChildBody as analogs of Frame::ResolveAttachedToBody [...]

I'm actually not sure why this is necessary... Is it just sugar?

**Comment by scpeters** [comment]
> > In order to figure out which are actually the parent and child links of a joint now, I think we should add Joint::ResolveParentBody and Joint::ResolveChildBody as analogs of Frame::ResolveAttachedToBody [...]
> 
> I'm actually not sure why this is necessary... Is it just sugar?
> Why can't you just do `Joint.ResolveParentFrame().ResolveAttachedToBody()`?

only the `Frame` class has a `ResolveAttachedToBody` method, so I'm not sure how this would work. We aren't using inheritance for the `Link`, `Joint`, and `Frame` classes, so what kind of object would be returned from `Joint.ResolveParentFrame()`?

perhaps we should consider another class like `SemanticPose` that provides the interface to resolving `FrameAttachedToGraph` queries?

**Comment by scpeters** [comment]
> perhaps we should consider another class like `SemanticPose` that provides the interface to resolving `FrameAttachedToGraph` queries?

it looks like this discussion is being addressed in https://github.com/osrf/sdf_tutorials/pull/3

**Comment by EricCousineau-TRI** [comment]
Per VC, we stick to philosophy that `SemanticPose` is a *temporary* view into an immutable graph, we can just pass it `attached_to` at construction time.

Different resolution for osrf/sdf_tutorials#3

**Comment by EricCousineau-TRI** [comment]
From @azeey: Should aim towards using `Link`, not `Body`.

From @scpeters: Reason is that the `attached_to` can be either a link, sibling model, or "world".
So "body" is an attempt to generalize...

**Comment by scpeters** [comment]
after discussing today with @azeey, we reached consensus on `Joint::ResolveChildLink` and `Joint::ResolveParentLink`, and I've incorporated this into #304. I closed the draft PR #300 because the deprecations were too noisy for a PR adding functionality. We can rename the API's in a follow-up PR.
