### ISSUE TITLE
AirPressure Move Constructor is not marked noexcept

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/sdformat#225]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/225)) by Michael Carroll (Bitbucket: [Michael Carroll](https://bitbucket.org/%7B17dbbc15-cbc0-42f0-a985-cde9061c78a0%7D/), GitHub: [mjcarroll](https://github.com/mjcarroll)).**

----------------------------------------
It should be marked noexcept like the rest of the move constructors, but would require an ABI break.

**Comment by azeey** [comment]
`AirPressure` uses `IMPL_PTR` from ign-utils starting from `sdf12`, which solves this issue.
