### ISSUE TITLE
Remove QUIET from SearchForStuff.cmake

### ISSUE THREAD

**Issue by werner291** [gazebosim/sdformat#469]
Hello! I was trying to build `sdformat` through Nix, and spent quite some time debugging due to CMake complaining about not being able to find ingition-math. After removing the QUIET directive from here:

https://github.com/osrf/sdformat/blob/master/cmake/SearchForStuff.cmake#L113

...CMake printed out that it was declaring the math package as "not found" because it couldn't find the ignition-cmake modules, not because it actually coulnd' find that module. Removing that directive could perhaps be useful to others who might run into this while porting sdformat to other linux distros.

**Comment by scpeters** [comment]
we aren't using SearchFromStuff.cmake anymore, and the find logic has changed a bit so I'll close this
