### ISSUE TITLE
Problem with Element::GetAttribute()/HasAttribute()/etc

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/sdformat#54]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/54)) by Jonathan Bohren (Bitbucket: [jbohren](https://bitbucket.org/%7B588087c1-4405-46da-b019-43f00b894b30%7D/)).**

----------------------------------------
If an sdf plugin tag has custom child tags, are those tags allowed to have attributes?

I tried loading some custom tags in a plugin, but the tag attributes don't seem to be loaded. If I put the same information in child tags it does work.

For example, SDF `Element::GetAttributeCount()` returns `0` for the following child tag of a plugin tag:
```xml
<custom foo="somevalue"/>
```

**Comment by scpeters** [comment]
custom attributes are now supported in custom elements according to the following proposal

* http://sdformat.org/tutorials?tut=custom_elements_attributes_proposal&cat=pose_semantics_docs&

I have confirmed this by updating an existing test in #1406
