### ISSUE TITLE
Consider deprecating unused `urdf.sdf`?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [gazebosim/sdformat#635]
## Environment
N/A

## Description
See: https://github.com/ignitionrobotics/sdformat/pull/589#discussion_r673546463

`urdf.sdf` doesn't seem to be used by the parser?

## Steps to reproduce
N/A

## Output
N/A

\cc @azeey

**Comment by scpeters** [comment]
I've proposed that unused file for removal in https://github.com/gazebosim/sdformat/pull/1113

**Comment by scpeters** [comment]
fixed by https://github.com/gazebosim/sdformat/pull/1113
