### ISSUE TITLE
Error when attributes in custom elements have empty values

### ISSUE THREAD

**Issue by azeey** [gazebosim/sdformat#725]
## Environment
* OS Version: 
* Source or binary build? source, `sdf9`

## Description
* Expected behavior: Users should be able to use empty strings for the values of their custom attributes without any errors.
* Actual behavior: When attributes in custom or unrecognized elements have empty values, the parser emits an error stating that an empty string may not be used for a required parameter. 

Related: 
 * https://github.com/ignitionrobotics/sdformat/issues/20
 * https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/pull-requests/111/page/1

## Steps to reproduce

1. Save the following to a file and run `ign sdf -k <file name>`
```xml
<sdf version="1.7" xmlns:custom="http://example.org/schema">
  <world name="default">
    <custom:foo attr1=""/>
  </world>
</sdf>
```

## Output
```
Error [Param.cc:473] Empty string used when setting a required parameter. Key[attr1]
Error [Param.cc:473] Empty string used when setting a required parameter. Key[attr1]
Valid.
```

**Comment by scpeters** [comment]
updated tests and added a fix in https://github.com/gazebosim/sdformat/pull/1407
