### ISSUE TITLE
add joint velocity and joint acceleration to state structure

### ISSUE THREAD

**Issue by osrf-migration** [gazebosim/sdformat#83]
**Original report ([archived issue](https://osrf-migration.github.io/sdformat-gh-pages/#!/osrf/sdformat/issues/83)) by John Hsu (Bitbucket: [hsu](https://bitbucket.org/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D/), GitHub: [hsu](https://github.com/hsu)).**

----------------------------------------
Add `velocity` and `acceleration` to [joint element](https://github.com/osrf/sdformat/blob/6281840305ed24b03e755f566bc3d08e178d99be/sdf/1.5/state.sdf#L45) for completeness.

@erwincoumans

@scpeters

**Comment by scpeters** [comment]
joint angle has been renamed to position, and velocity, acceleration, and effort states have been added to SDFormat 1.12 in https://github.com/gazebosim/sdformat/pull/1461
