### ISSUE TITLE
Link needs helper function to get Inertial relative to a named frame

### ISSUE THREAD

**Issue by scpeters** [gazebosim/sdformat#935]
## Desired behavior

Currently the `Link::Inertial()` accessor returns an `Inertial` object with the `Pose` specified relative to the link frame. Since there is no `sdf::Inertial` class with a `SemanticPose()` API, it would be nice to provide a `Link::ResolveInertial(ignition::math::Inertiald &_inertial, const std::string &_resolveTo = "")` method that would resolve the `Inertial`'s `Pose` to a specified frame, such as `__model__`.

## Alternatives considered

We could create an `sdf::Inertial` object or just leave the API as is and provide documentation for how to resolve multiple `Inertial` objects to a common frame.

## Implementation suggestion

~~~
Errors Link::ResolveInertial(
  ignition::math::Inertiald &_inertial,
  const std::string &_resolveTo = "")
{
  ignition::math::Pose3d linkPose;
  auto errors = this->SemanticPose().Resolve(linkPose, _resolveTo);
  if (errors.empty())
  {
    _inertial.SetPose(linkPose * _inertial.Pose());
  }
  return errors;
}
~~~

**Comment by azeey** [comment]
This sounds useful and the implementation suggestion looks good. There's precedent for doing this type of thing in `JointAxis::ResolveXyz`. This would also mean we can add `//inertal/pose/@relative_to` easily.

**Comment by scpeters** [comment]
see #1012
