### ISSUE TITLE
Consider renaming Joint::ParentLinkName and Joint::ChildLinkName to Joint::ParentName and Joint::ChildName

### ISSUE THREAD

**Issue by azeey** [gazebosim/sdformat#979]
## Desired behavior
As of SDFormat 1.8, joints can have frames as parent or child elements, so the functions `Joint::ParentLinkName` and `Joint::ChildLinkName` are no longer accurate. My suggestion would be to rename them to `Joint::ParentName` and `Joint::ChildName`.

## Alternatives considered
They could also be named `Joint::ParentFrameName` and `Joint::ChildFrameName` since all parent/child elements are frames, either explicit or implicit. However, I think this is a little more confusing if users are not familiar with the explicit/implicit frame concept.

**Comment by scpeters** [comment]
see #1053
